### ISSUE TITLE
basic_common_reference constrained to const refs

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdox#374]
See: https://github.com/cppalliance/mrdox/blob/develop/include/mrdox/Support/Dom.hpp#L1352

**Comment by sdkrystian** [comment]
I'm not sure I understand. `Object::reference` functions as a `const` proxy reference for an object -- meaning, `std::common_reference_t<Object::value_type, Object:: reference>` should always result in `Object::reference` because `Object::reference` can be initialized with an object of type "`cv` `Object::reference`" or "`cv` `Object::value_type`" regardless of what `cv` is (well, so long `cv` does not contain  `volatile`). Am missing something?

**Comment by vinniefalco** [comment]
I don't know. If you think this is right, then its probably right.

**Comment by vinniefalco** [comment]
@sdkrystian if you believe this code is correct then please close the issue.
